services:
  redmine:
    container_name: redmine
    build:
      context: .
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 512m
    ports:
      - 127.0.0.1:8003:3000
    networks:
      - postgres14
    environment:
      # TODO: use postgres17 on Redmine
      REDMINE_DB_POSTGRES: postgres14
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
    volumes:
      - ~/OneDrive/Apps/Redmine/files:/usr/src/redmine/files
      # Themes should be manually downloaded to this directory below (the left one):
      # - ~/OneDrive/Apps/Redmine/themes:/usr/src/redmine/public/custom-themes
      # TODO feat: download custom themes inside the Dockerfile

networks:
  postgres14:
    name: postgres14
    external: true
