# https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/docker.html#creating-a-strapi-project
version: "3"

networks:
  postgres17:
    external: true

services:
  strapi:
    container_name: strapi
    # https://hub.docker.com/r/strapi/strapi
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres17
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: ${STRAPI_DATABASE_PASSWORD}
      # https://strapi.io/documentation/3.0.0-beta.x/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging
      # NODE_ENV: production
    networks:
      - postgres17
    volumes:
      # Change the database on a JSON file with:
      # rg postgres17 strapi/ -l | xargs code
      - ./app:/srv/app
    ports:
      - "1337:1337"
    # To fix the error 'Something went wrong installing the "sharp" module', uncomment this line:
    # command: npm install --ignore-scripts=false --verbose
    # See https://github.com/lovell/sharp/issues/2026#issuecomment-572175140
